version: "3.3"

services:
  postgres:
    image: postgres:14.3
    ports:
      - 5433:5432
    volumes:
      - "./.postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "audiolinx"

  # redis:
  #   image: redis:6.2.5
  #   ports:
  #     - "6380:6379"
  #   volumes:
  #     - "./.redis:/data"
